disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_parameter_alignment_on_call

included:
  - FeishuSpeech

excluded:
  - FeishuSpeechTests
  - FeishuSpeech/Resources

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - URL

function_parameter_count:
  warning: 5
  error: 8

nesting:
  type_level:
    warning: 2

reporter: "xcode"
